### ISSUE TITLE
Relative jump addresses calculated incorrectly

### ISSUE THREAD

**Issue by ramo48859** [kcelebi/riscv-assembler#14]
Hi,
in function `calcJump(self,lineNumber)` the relative addresses of labels are calculated incorrectly. More specifically, labels before the label of interest are counted as well, leading to jumps further than anticipated.

....
   addi t0, x0, 1
   blt a1, t0, exit7    <---- this address is calculated correctly
    j loop_start        <-----this one is one to high due to
exit7:                     <-----this label
    li a1, 7
    j exit2

loop_start:
    addi t0, x0,0 #i =0
    addi t1, x0, 0, #max val <---- jumps to this instruction
    addi t2, x0, 0 #iteration comp
....

BR,
David

**Comment by kcelebi** [comment]
Thank you for this comment. The version that provided this buggy calcJump is now deprecated and the updated version works for this example. 

Note: I won't be updating this repository anymore as it has been moved to [celebi-pkg/riscv-assembler](https://www.github.com/celebi-pkg/riscv-assembler). The Python deployments and latest code are being updated there.
