### ISSUE TITLE
ld instruction not working. "KeyError: <immediate_value>" shows up

### ISSUE THREAD

**Issue by burhanuddin6** [kcelebi/riscv-assembler#25]
![image](https://user-images.githubusercontent.com/98301121/231271761-81ffddc2-5e0a-48b6-8ab0-16cf1a561540.png)
throws this error:
![image](https://user-images.githubusercontent.com/98301121/231271936-d738da04-81b9-44d6-93cf-080f289561df.png)

**Comment by burhanuddin6** [comment]
remove the else condition in line 214 + unindent line 213. Line 213 is correct but line 215 is not. The reg_map[tokens[2]] is causing error because tokens[2] equals the immediate value, resulting in keyerror.
![image](https://user-images.githubusercontent.com/98301121/231277995-74bffe06-7ce4-49b9-a3bf-e822d097e539.png)

**Comment by kcelebi** [comment]
Thank you for pointing this out and for providing all of this information. I will take a look at this immediately and update once finished.

Note: I won't be updating this repository anymore as it has been moved to [celebi-pkg/riscv-assembler](https://www.github.com/celebi-pkg/riscv-assembler). The Python deployments and latest code are being updated there.

**Comment by kcelebi** [comment]
Just pushed some updates and many unit tests to cover this problem, also uploaded v1.2.0 on PyPI. Closing issue as resolved.
