### ISSUE TITLE
Bug in SB_type() in AssemblyConvertor class

### ISSUE THREAD

**Issue by shudaniel** [kcelebi/riscv-assembler#5]
On line 271, it should be self.instr_data instead of instr_data. 
Otherwise you will get a "NameError: name 'instr_data' is not defined"

**Comment by kcelebi** [comment]
Which file is this referring to? I don't seem to see this error in either convert.py or utils.py.

It's possible that you're seeing this error because I haven't actually updated the package on PyPI, in which case I'll push an update to that now.

**Comment by shudaniel** [comment]
I was looking at the source code from the PyPI package I downloaded in convert.py, so I guess it just needs to be updated.

**Comment by kcelebi** [comment]
Ok just updated it, I'll leave this issue open for a little in case there's still a problem
