### ISSUE TITLE
li not converted properly for large immediates.

### ISSUE THREAD

**Issue by origamiman72** [kcelebi/riscv-assembler#6]
https://github.com/kcelebi/riscv-assembler/blob/a2cfe01c93a4f35afd3e46a8abcb1cd5e8d98865/riscv_assembler/convert.py#L444

When given an immediate over 12 bits, `li` should be converted into a combination of `lui` to load the upper bits and `addi` to load the lower bits.
e.g. `li x0, 0x1111111` converts into these two instructions:
![image](https://user-images.githubusercontent.com/25716711/113405930-793ab980-935f-11eb-9210-3e31d51249cb.png)
(screenshot source: https://venus.cs61c.org)

**Comment by kcelebi** [comment]
Great catch, slipped my mind to consider an immediate over 12 bits. Currently adding some new features so I'll include this fix, thank you!

I'll keep the issue open until I resolve it

**Comment by kcelebi** [comment]
Seem to have fixed the issue and it's passing tests, I'll merge it into the main branch once I'm done adding some other features. Closing issue.
